---
title: Watchdog Findings
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Watchdog Findings is a publication based on reports created by Watchdog
  Research, Inc.
encoding: utf-8
permalink: pretty
rss: rss
twitter_username: CWD_Research
google_analytics: UA-116841703-3
plugins:
- jekyll-seo-tag
- jekyll-feed
markdown: kramdown
include:
- 404.html
exclude:
- ".idea"
authors:
  olga_usvyatsky:
    name: Olga Usvyatsky
    email: ousvyatsky@ivesinc.com
  joseph_burke:
    name: Joseph Burke
    email: jburke@cwdresearch.com
  brian_lawe:
    name: Brian Lawe
  john_cheffers:
    name: John Cheffers
url: https://blog.cwdresearch.com
