---
title: Watchdog Transparency Blog
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Watchdog Transparency is a publication based on reports created by Watchdog
  Research, Inc.
encoding: utf-8
permalink: pretty
rss: rss
twitter_username: CWD_Research
google_analytics: UA-116841703-3
plugins:
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
- jekyll-archives
jekyll-archives:
  enabled:
  - month
  layout: default
  permalinks:
    month: "/archives/:year/:month/"
  layouts:
    month: month_archive
markdown: kramdown
sass:
  sass_dir: _sass
  style: compact
include:
- 404.html
exclude:
- ".idea"
authors:
  olga_usvyatsky:
    name: Olga Usvyatsky
    email: ousvyatsky@ivesinc.com
  joseph_burke:
    name: Joseph Burke
    email: jburke@watchdogresearch.com
  brian_lawe:
    name: Brian Lawe
  john_cheffers:
    name: John Cheffers
url: https://blog.watchdogresearch.com
paginate: 7
paginate_path: "/page:num/"
