source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end



gem 'jekyll'


gem 'jekyll-seo-tag'
gem 'jekyll-feed'
